# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 23:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_text', models.CharField(default='', max_length=2000)),
                ('audio_filename', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default='', verbose_name='date published')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.CharField(max_length=2000)),
                ('chinese_text', models.CharField(default='', max_length=2000)),
                ('audio_filename', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default='', verbose_name='date published')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
