# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='sentence',
            name='sentence_text',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
