# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_sentence_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='chinese_text',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
