# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_sentence_chinese_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='translated_text',
            field=models.SlugField(allow_unicode=True, default='', max_length=2000),
        ),
    ]
