# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 23:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_sentence_translated_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='translated_text',
        ),
        migrations.AddField(
            model_name='sentence',
            name='text_recording',
            field=models.FileField(default='', max_length=2000, upload_to=django.core.files.storage.FileSystemStorage(location='/saved_words')),
        ),
    ]
