# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 01:38
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20160511_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='text_recording',
            field=models.FileField(default='', max_length=2000, storage=django.core.files.storage.FileSystemStorage(location='/saved_words'), upload_to=''),
        ),
    ]
