# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='a title', max_length=200)),
                ('video_link', models.CharField(max_length=200)),
            ],
        ),
    ]
