# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='a title', max_length=200),
        ),
    ]
